# Generated by Django 3.2.3 on 2021-05-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardsapp', '0002_alter_ratings_rater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwardsapp.profile'),
        ),
    ]
